name: Package
on: [push]
jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Install Dependencies
        run: sudo apt-get install -y dpkg-dev python3 python3-pip
      - name: Install Python Minifier
        run: pip3 install python-minifier
      - name: Package
        run: ./scripts/package.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian
          path: |
            out
